# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/max/castor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/max/castor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/max/castor/CMakeFiles /Users/max/castor/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/max/castor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Castor

# Build rule for target.
Castor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Castor
.PHONY : Castor

# fast build rule for target.
Castor/fast:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/build
.PHONY : Castor/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

src/CastorApplication.o: src/CastorApplication.cpp.o

.PHONY : src/CastorApplication.o

# target to build an object file
src/CastorApplication.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/CastorApplication.cpp.o
.PHONY : src/CastorApplication.cpp.o

src/CastorApplication.i: src/CastorApplication.cpp.i

.PHONY : src/CastorApplication.i

# target to preprocess a source file
src/CastorApplication.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/CastorApplication.cpp.i
.PHONY : src/CastorApplication.cpp.i

src/CastorApplication.s: src/CastorApplication.cpp.s

.PHONY : src/CastorApplication.s

# target to generate assembly for a file
src/CastorApplication.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/CastorApplication.cpp.s
.PHONY : src/CastorApplication.cpp.s

src/CompositePIPmsa.o: src/CompositePIPmsa.cpp.o

.PHONY : src/CompositePIPmsa.o

# target to build an object file
src/CompositePIPmsa.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/CompositePIPmsa.cpp.o
.PHONY : src/CompositePIPmsa.cpp.o

src/CompositePIPmsa.i: src/CompositePIPmsa.cpp.i

.PHONY : src/CompositePIPmsa.i

# target to preprocess a source file
src/CompositePIPmsa.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/CompositePIPmsa.cpp.i
.PHONY : src/CompositePIPmsa.cpp.i

src/CompositePIPmsa.s: src/CompositePIPmsa.cpp.s

.PHONY : src/CompositePIPmsa.s

# target to generate assembly for a file
src/CompositePIPmsa.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/CompositePIPmsa.cpp.s
.PHONY : src/CompositePIPmsa.cpp.s

src/CompositePIPnode.o: src/CompositePIPnode.cpp.o

.PHONY : src/CompositePIPnode.o

# target to build an object file
src/CompositePIPnode.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/CompositePIPnode.cpp.o
.PHONY : src/CompositePIPnode.cpp.o

src/CompositePIPnode.i: src/CompositePIPnode.cpp.i

.PHONY : src/CompositePIPnode.i

# target to preprocess a source file
src/CompositePIPnode.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/CompositePIPnode.cpp.i
.PHONY : src/CompositePIPnode.cpp.i

src/CompositePIPnode.s: src/CompositePIPnode.cpp.s

.PHONY : src/CompositePIPnode.s

# target to generate assembly for a file
src/CompositePIPnode.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/CompositePIPnode.cpp.s
.PHONY : src/CompositePIPnode.cpp.s

src/ExtendedAlphabet.o: src/ExtendedAlphabet.cpp.o

.PHONY : src/ExtendedAlphabet.o

# target to build an object file
src/ExtendedAlphabet.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/ExtendedAlphabet.cpp.o
.PHONY : src/ExtendedAlphabet.cpp.o

src/ExtendedAlphabet.i: src/ExtendedAlphabet.cpp.i

.PHONY : src/ExtendedAlphabet.i

# target to preprocess a source file
src/ExtendedAlphabet.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/ExtendedAlphabet.cpp.i
.PHONY : src/ExtendedAlphabet.cpp.i

src/ExtendedAlphabet.s: src/ExtendedAlphabet.cpp.s

.PHONY : src/ExtendedAlphabet.s

# target to generate assembly for a file
src/ExtendedAlphabet.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/ExtendedAlphabet.cpp.s
.PHONY : src/ExtendedAlphabet.cpp.s

src/FactoryPIPnodeCPU.o: src/FactoryPIPnodeCPU.cpp.o

.PHONY : src/FactoryPIPnodeCPU.o

# target to build an object file
src/FactoryPIPnodeCPU.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/FactoryPIPnodeCPU.cpp.o
.PHONY : src/FactoryPIPnodeCPU.cpp.o

src/FactoryPIPnodeCPU.i: src/FactoryPIPnodeCPU.cpp.i

.PHONY : src/FactoryPIPnodeCPU.i

# target to preprocess a source file
src/FactoryPIPnodeCPU.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/FactoryPIPnodeCPU.cpp.i
.PHONY : src/FactoryPIPnodeCPU.cpp.i

src/FactoryPIPnodeCPU.s: src/FactoryPIPnodeCPU.cpp.s

.PHONY : src/FactoryPIPnodeCPU.s

# target to generate assembly for a file
src/FactoryPIPnodeCPU.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/FactoryPIPnodeCPU.cpp.s
.PHONY : src/FactoryPIPnodeCPU.cpp.s

src/FactoryPIPnodeRAM.o: src/FactoryPIPnodeRAM.cpp.o

.PHONY : src/FactoryPIPnodeRAM.o

# target to build an object file
src/FactoryPIPnodeRAM.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/FactoryPIPnodeRAM.cpp.o
.PHONY : src/FactoryPIPnodeRAM.cpp.o

src/FactoryPIPnodeRAM.i: src/FactoryPIPnodeRAM.cpp.i

.PHONY : src/FactoryPIPnodeRAM.i

# target to preprocess a source file
src/FactoryPIPnodeRAM.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/FactoryPIPnodeRAM.cpp.i
.PHONY : src/FactoryPIPnodeRAM.cpp.i

src/FactoryPIPnodeRAM.s: src/FactoryPIPnodeRAM.cpp.s

.PHONY : src/FactoryPIPnodeRAM.s

# target to generate assembly for a file
src/FactoryPIPnodeRAM.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/FactoryPIPnodeRAM.cpp.s
.PHONY : src/FactoryPIPnodeRAM.cpp.s

src/FactoryPIPnodeSB.o: src/FactoryPIPnodeSB.cpp.o

.PHONY : src/FactoryPIPnodeSB.o

# target to build an object file
src/FactoryPIPnodeSB.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/FactoryPIPnodeSB.cpp.o
.PHONY : src/FactoryPIPnodeSB.cpp.o

src/FactoryPIPnodeSB.i: src/FactoryPIPnodeSB.cpp.i

.PHONY : src/FactoryPIPnodeSB.i

# target to preprocess a source file
src/FactoryPIPnodeSB.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/FactoryPIPnodeSB.cpp.i
.PHONY : src/FactoryPIPnodeSB.cpp.i

src/FactoryPIPnodeSB.s: src/FactoryPIPnodeSB.cpp.s

.PHONY : src/FactoryPIPnodeSB.s

# target to generate assembly for a file
src/FactoryPIPnodeSB.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/FactoryPIPnodeSB.cpp.s
.PHONY : src/FactoryPIPnodeSB.cpp.s

src/LambertW.o: src/LambertW.cc.o

.PHONY : src/LambertW.o

# target to build an object file
src/LambertW.cc.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/LambertW.cc.o
.PHONY : src/LambertW.cc.o

src/LambertW.i: src/LambertW.cc.i

.PHONY : src/LambertW.i

# target to preprocess a source file
src/LambertW.cc.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/LambertW.cc.i
.PHONY : src/LambertW.cc.i

src/LambertW.s: src/LambertW.cc.s

.PHONY : src/LambertW.s

# target to generate assembly for a file
src/LambertW.cc.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/LambertW.cc.s
.PHONY : src/LambertW.cc.s

src/Optimizators.o: src/Optimizators.cpp.o

.PHONY : src/Optimizators.o

# target to build an object file
src/Optimizators.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/Optimizators.cpp.o
.PHONY : src/Optimizators.cpp.o

src/Optimizators.i: src/Optimizators.cpp.i

.PHONY : src/Optimizators.i

# target to preprocess a source file
src/Optimizators.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/Optimizators.cpp.i
.PHONY : src/Optimizators.cpp.i

src/Optimizators.s: src/Optimizators.cpp.s

.PHONY : src/Optimizators.s

# target to generate assembly for a file
src/Optimizators.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/Optimizators.cpp.s
.PHONY : src/Optimizators.cpp.s

src/PIP.o: src/PIP.cpp.o

.PHONY : src/PIP.o

# target to build an object file
src/PIP.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/PIP.cpp.o
.PHONY : src/PIP.cpp.o

src/PIP.i: src/PIP.cpp.i

.PHONY : src/PIP.i

# target to preprocess a source file
src/PIP.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/PIP.cpp.i
.PHONY : src/PIP.cpp.i

src/PIP.s: src/PIP.cpp.s

.PHONY : src/PIP.s

# target to generate assembly for a file
src/PIP.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/PIP.cpp.s
.PHONY : src/PIP.cpp.s

src/PIPmsa.o: src/PIPmsa.cpp.o

.PHONY : src/PIPmsa.o

# target to build an object file
src/PIPmsa.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/PIPmsa.cpp.o
.PHONY : src/PIPmsa.cpp.o

src/PIPmsa.i: src/PIPmsa.cpp.i

.PHONY : src/PIPmsa.i

# target to preprocess a source file
src/PIPmsa.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/PIPmsa.cpp.i
.PHONY : src/PIPmsa.cpp.i

src/PIPmsa.s: src/PIPmsa.cpp.s

.PHONY : src/PIPmsa.s

# target to generate assembly for a file
src/PIPmsa.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/PIPmsa.cpp.s
.PHONY : src/PIPmsa.cpp.s

src/PIPnode.o: src/PIPnode.cpp.o

.PHONY : src/PIPnode.o

# target to build an object file
src/PIPnode.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/PIPnode.cpp.o
.PHONY : src/PIPnode.cpp.o

src/PIPnode.i: src/PIPnode.cpp.i

.PHONY : src/PIPnode.i

# target to preprocess a source file
src/PIPnode.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/PIPnode.cpp.i
.PHONY : src/PIPnode.cpp.i

src/PIPnode.s: src/PIPnode.cpp.s

.PHONY : src/PIPnode.s

# target to generate assembly for a file
src/PIPnode.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/PIPnode.cpp.s
.PHONY : src/PIPnode.cpp.s

src/RHomogeneousTreeLikelihood_Generic.o: src/RHomogeneousTreeLikelihood_Generic.cpp.o

.PHONY : src/RHomogeneousTreeLikelihood_Generic.o

# target to build an object file
src/RHomogeneousTreeLikelihood_Generic.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/RHomogeneousTreeLikelihood_Generic.cpp.o
.PHONY : src/RHomogeneousTreeLikelihood_Generic.cpp.o

src/RHomogeneousTreeLikelihood_Generic.i: src/RHomogeneousTreeLikelihood_Generic.cpp.i

.PHONY : src/RHomogeneousTreeLikelihood_Generic.i

# target to preprocess a source file
src/RHomogeneousTreeLikelihood_Generic.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/RHomogeneousTreeLikelihood_Generic.cpp.i
.PHONY : src/RHomogeneousTreeLikelihood_Generic.cpp.i

src/RHomogeneousTreeLikelihood_Generic.s: src/RHomogeneousTreeLikelihood_Generic.cpp.s

.PHONY : src/RHomogeneousTreeLikelihood_Generic.s

# target to generate assembly for a file
src/RHomogeneousTreeLikelihood_Generic.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/RHomogeneousTreeLikelihood_Generic.cpp.s
.PHONY : src/RHomogeneousTreeLikelihood_Generic.cpp.s

src/RHomogeneousTreeLikelihood_PIP.o: src/RHomogeneousTreeLikelihood_PIP.cpp.o

.PHONY : src/RHomogeneousTreeLikelihood_PIP.o

# target to build an object file
src/RHomogeneousTreeLikelihood_PIP.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/RHomogeneousTreeLikelihood_PIP.cpp.o
.PHONY : src/RHomogeneousTreeLikelihood_PIP.cpp.o

src/RHomogeneousTreeLikelihood_PIP.i: src/RHomogeneousTreeLikelihood_PIP.cpp.i

.PHONY : src/RHomogeneousTreeLikelihood_PIP.i

# target to preprocess a source file
src/RHomogeneousTreeLikelihood_PIP.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/RHomogeneousTreeLikelihood_PIP.cpp.i
.PHONY : src/RHomogeneousTreeLikelihood_PIP.cpp.i

src/RHomogeneousTreeLikelihood_PIP.s: src/RHomogeneousTreeLikelihood_PIP.cpp.s

.PHONY : src/RHomogeneousTreeLikelihood_PIP.s

# target to generate assembly for a file
src/RHomogeneousTreeLikelihood_PIP.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/RHomogeneousTreeLikelihood_PIP.cpp.s
.PHONY : src/RHomogeneousTreeLikelihood_PIP.cpp.s

src/SupportMeasures.o: src/SupportMeasures.cpp.o

.PHONY : src/SupportMeasures.o

# target to build an object file
src/SupportMeasures.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/SupportMeasures.cpp.o
.PHONY : src/SupportMeasures.cpp.o

src/SupportMeasures.i: src/SupportMeasures.cpp.i

.PHONY : src/SupportMeasures.i

# target to preprocess a source file
src/SupportMeasures.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/SupportMeasures.cpp.i
.PHONY : src/SupportMeasures.cpp.i

src/SupportMeasures.s: src/SupportMeasures.cpp.s

.PHONY : src/SupportMeasures.s

# target to generate assembly for a file
src/SupportMeasures.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/SupportMeasures.cpp.s
.PHONY : src/SupportMeasures.cpp.s

src/UnifiedDistanceEstimation.o: src/UnifiedDistanceEstimation.cpp.o

.PHONY : src/UnifiedDistanceEstimation.o

# target to build an object file
src/UnifiedDistanceEstimation.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedDistanceEstimation.cpp.o
.PHONY : src/UnifiedDistanceEstimation.cpp.o

src/UnifiedDistanceEstimation.i: src/UnifiedDistanceEstimation.cpp.i

.PHONY : src/UnifiedDistanceEstimation.i

# target to preprocess a source file
src/UnifiedDistanceEstimation.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedDistanceEstimation.cpp.i
.PHONY : src/UnifiedDistanceEstimation.cpp.i

src/UnifiedDistanceEstimation.s: src/UnifiedDistanceEstimation.cpp.s

.PHONY : src/UnifiedDistanceEstimation.s

# target to generate assembly for a file
src/UnifiedDistanceEstimation.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedDistanceEstimation.cpp.s
.PHONY : src/UnifiedDistanceEstimation.cpp.s

src/UnifiedPhylogeneticTools.o: src/UnifiedPhylogeneticTools.cpp.o

.PHONY : src/UnifiedPhylogeneticTools.o

# target to build an object file
src/UnifiedPhylogeneticTools.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedPhylogeneticTools.cpp.o
.PHONY : src/UnifiedPhylogeneticTools.cpp.o

src/UnifiedPhylogeneticTools.i: src/UnifiedPhylogeneticTools.cpp.i

.PHONY : src/UnifiedPhylogeneticTools.i

# target to preprocess a source file
src/UnifiedPhylogeneticTools.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedPhylogeneticTools.cpp.i
.PHONY : src/UnifiedPhylogeneticTools.cpp.i

src/UnifiedPhylogeneticTools.s: src/UnifiedPhylogeneticTools.cpp.s

.PHONY : src/UnifiedPhylogeneticTools.s

# target to generate assembly for a file
src/UnifiedPhylogeneticTools.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedPhylogeneticTools.cpp.s
.PHONY : src/UnifiedPhylogeneticTools.cpp.s

src/UnifiedTSHSearchable.o: src/UnifiedTSHSearchable.cpp.o

.PHONY : src/UnifiedTSHSearchable.o

# target to build an object file
src/UnifiedTSHSearchable.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHSearchable.cpp.o
.PHONY : src/UnifiedTSHSearchable.cpp.o

src/UnifiedTSHSearchable.i: src/UnifiedTSHSearchable.cpp.i

.PHONY : src/UnifiedTSHSearchable.i

# target to preprocess a source file
src/UnifiedTSHSearchable.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHSearchable.cpp.i
.PHONY : src/UnifiedTSHSearchable.cpp.i

src/UnifiedTSHSearchable.s: src/UnifiedTSHSearchable.cpp.s

.PHONY : src/UnifiedTSHSearchable.s

# target to generate assembly for a file
src/UnifiedTSHSearchable.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHSearchable.cpp.s
.PHONY : src/UnifiedTSHSearchable.cpp.s

src/UnifiedTSHTopologySearch.o: src/UnifiedTSHTopologySearch.cpp.o

.PHONY : src/UnifiedTSHTopologySearch.o

# target to build an object file
src/UnifiedTSHTopologySearch.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHTopologySearch.cpp.o
.PHONY : src/UnifiedTSHTopologySearch.cpp.o

src/UnifiedTSHTopologySearch.i: src/UnifiedTSHTopologySearch.cpp.i

.PHONY : src/UnifiedTSHTopologySearch.i

# target to preprocess a source file
src/UnifiedTSHTopologySearch.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHTopologySearch.cpp.i
.PHONY : src/UnifiedTSHTopologySearch.cpp.i

src/UnifiedTSHTopologySearch.s: src/UnifiedTSHTopologySearch.cpp.s

.PHONY : src/UnifiedTSHTopologySearch.s

# target to generate assembly for a file
src/UnifiedTSHTopologySearch.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHTopologySearch.cpp.s
.PHONY : src/UnifiedTSHTopologySearch.cpp.s

src/UnifiedTSHomogeneousTreeLikelihood_Generic.o: src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.o

.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_Generic.o

# target to build an object file
src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.o
.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.o

src/UnifiedTSHomogeneousTreeLikelihood_Generic.i: src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.i

.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_Generic.i

# target to preprocess a source file
src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.i
.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.i

src/UnifiedTSHomogeneousTreeLikelihood_Generic.s: src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.s

.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_Generic.s

# target to generate assembly for a file
src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.s
.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_Generic.cpp.s

src/UnifiedTSHomogeneousTreeLikelihood_PIP.o: src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.o

.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_PIP.o

# target to build an object file
src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.o
.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.o

src/UnifiedTSHomogeneousTreeLikelihood_PIP.i: src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.i

.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_PIP.i

# target to preprocess a source file
src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.i
.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.i

src/UnifiedTSHomogeneousTreeLikelihood_PIP.s: src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.s

.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_PIP.s

# target to generate assembly for a file
src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.s
.PHONY : src/UnifiedTSHomogeneousTreeLikelihood_PIP.cpp.s

src/Utils.o: src/Utils.cpp.o

.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i

.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s

.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/pPIP.o: src/pPIP.cpp.o

.PHONY : src/pPIP.o

# target to build an object file
src/pPIP.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/pPIP.cpp.o
.PHONY : src/pPIP.cpp.o

src/pPIP.i: src/pPIP.cpp.i

.PHONY : src/pPIP.i

# target to preprocess a source file
src/pPIP.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/pPIP.cpp.i
.PHONY : src/pPIP.cpp.i

src/pPIP.s: src/pPIP.cpp.s

.PHONY : src/pPIP.s

# target to generate assembly for a file
src/pPIP.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/pPIP.cpp.s
.PHONY : src/pPIP.cpp.s

src/progressivePIP.o: src/progressivePIP.cpp.o

.PHONY : src/progressivePIP.o

# target to build an object file
src/progressivePIP.cpp.o:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/progressivePIP.cpp.o
.PHONY : src/progressivePIP.cpp.o

src/progressivePIP.i: src/progressivePIP.cpp.i

.PHONY : src/progressivePIP.i

# target to preprocess a source file
src/progressivePIP.cpp.i:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/progressivePIP.cpp.i
.PHONY : src/progressivePIP.cpp.i

src/progressivePIP.s: src/progressivePIP.cpp.s

.PHONY : src/progressivePIP.s

# target to generate assembly for a file
src/progressivePIP.cpp.s:
	$(MAKE) -f CMakeFiles/Castor.dir/build.make CMakeFiles/Castor.dir/src/progressivePIP.cpp.s
.PHONY : src/progressivePIP.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousStart"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalStart"
	@echo "... ContinuousSubmit"
	@echo "... ExperimentalTest"
	@echo "... NightlySubmit"
	@echo "... NightlyMemCheck"
	@echo "... test"
	@echo "... ExperimentalConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyTest"
	@echo "... ContinuousMemCheck"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyUpdate"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalUpdate"
	@echo "... Continuous"
	@echo "... Castor"
	@echo "... ExperimentalMemCheck"
	@echo "... edit_cache"
	@echo "... ContinuousConfigure"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... Nightly"
	@echo "... Experimental"
	@echo "... src/CastorApplication.o"
	@echo "... src/CastorApplication.i"
	@echo "... src/CastorApplication.s"
	@echo "... src/CompositePIPmsa.o"
	@echo "... src/CompositePIPmsa.i"
	@echo "... src/CompositePIPmsa.s"
	@echo "... src/CompositePIPnode.o"
	@echo "... src/CompositePIPnode.i"
	@echo "... src/CompositePIPnode.s"
	@echo "... src/ExtendedAlphabet.o"
	@echo "... src/ExtendedAlphabet.i"
	@echo "... src/ExtendedAlphabet.s"
	@echo "... src/FactoryPIPnodeCPU.o"
	@echo "... src/FactoryPIPnodeCPU.i"
	@echo "... src/FactoryPIPnodeCPU.s"
	@echo "... src/FactoryPIPnodeRAM.o"
	@echo "... src/FactoryPIPnodeRAM.i"
	@echo "... src/FactoryPIPnodeRAM.s"
	@echo "... src/FactoryPIPnodeSB.o"
	@echo "... src/FactoryPIPnodeSB.i"
	@echo "... src/FactoryPIPnodeSB.s"
	@echo "... src/LambertW.o"
	@echo "... src/LambertW.i"
	@echo "... src/LambertW.s"
	@echo "... src/Optimizators.o"
	@echo "... src/Optimizators.i"
	@echo "... src/Optimizators.s"
	@echo "... src/PIP.o"
	@echo "... src/PIP.i"
	@echo "... src/PIP.s"
	@echo "... src/PIPmsa.o"
	@echo "... src/PIPmsa.i"
	@echo "... src/PIPmsa.s"
	@echo "... src/PIPnode.o"
	@echo "... src/PIPnode.i"
	@echo "... src/PIPnode.s"
	@echo "... src/RHomogeneousTreeLikelihood_Generic.o"
	@echo "... src/RHomogeneousTreeLikelihood_Generic.i"
	@echo "... src/RHomogeneousTreeLikelihood_Generic.s"
	@echo "... src/RHomogeneousTreeLikelihood_PIP.o"
	@echo "... src/RHomogeneousTreeLikelihood_PIP.i"
	@echo "... src/RHomogeneousTreeLikelihood_PIP.s"
	@echo "... src/SupportMeasures.o"
	@echo "... src/SupportMeasures.i"
	@echo "... src/SupportMeasures.s"
	@echo "... src/UnifiedDistanceEstimation.o"
	@echo "... src/UnifiedDistanceEstimation.i"
	@echo "... src/UnifiedDistanceEstimation.s"
	@echo "... src/UnifiedPhylogeneticTools.o"
	@echo "... src/UnifiedPhylogeneticTools.i"
	@echo "... src/UnifiedPhylogeneticTools.s"
	@echo "... src/UnifiedTSHSearchable.o"
	@echo "... src/UnifiedTSHSearchable.i"
	@echo "... src/UnifiedTSHSearchable.s"
	@echo "... src/UnifiedTSHTopologySearch.o"
	@echo "... src/UnifiedTSHTopologySearch.i"
	@echo "... src/UnifiedTSHTopologySearch.s"
	@echo "... src/UnifiedTSHomogeneousTreeLikelihood_Generic.o"
	@echo "... src/UnifiedTSHomogeneousTreeLikelihood_Generic.i"
	@echo "... src/UnifiedTSHomogeneousTreeLikelihood_Generic.s"
	@echo "... src/UnifiedTSHomogeneousTreeLikelihood_PIP.o"
	@echo "... src/UnifiedTSHomogeneousTreeLikelihood_PIP.i"
	@echo "... src/UnifiedTSHomogeneousTreeLikelihood_PIP.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/pPIP.o"
	@echo "... src/pPIP.i"
	@echo "... src/pPIP.s"
	@echo "... src/progressivePIP.o"
	@echo "... src/progressivePIP.i"
	@echo "... src/progressivePIP.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

